name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Instalação do Google Chrome
      run: sudo apt-get update && sudo apt-get install google-chrome-stable

    - name: Install Selenium
        run: |
            sudo pip3 install selenium
      - name: ChromeWebDriver
        run: |
            cat <<EOF >> test.py
            from selenium import webdriver
            from selenium.webdriver.chrome.options import Options
            options = Options()
            options.add_argument("--headless")
            options.add_argument('--no-sandbox')
            options.add_argument('--disable-gpu')
            options.add_argument('--disable-dev-shm-usage')
            options.add_argument('disable-infobars')
            options.add_argument("--disable-extensions")
            driver = webdriver.Chrome(chrome_options=options, executable_path='/usr/bin/chromedriver')
            driver.get("http://github.com/")
            print ('Page title is ' + driver.title)
            EOF
            
            python3 test.py

    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      #uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
      with:
        ruby-version: 2.7
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      
    - name: Install bundler
      run: gem install bundler

    - name: Install dependencies
      run:
          gem install capybara cucumber rspec selenium-webdriver site_prism pry
      

    - name: Execute test
      run:
          bundler exec cucumber

