name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
   
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      #uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
      with:
        ruby-version: latest
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      
    - name: Execute test
      run:
          bundle exec cucumber -p ci --format html --out ./reports/relatorio.html
          
    - name: Step 4 Archive production artifacts
      uses: actions/upload-artifact@v2
      with: 
          name: reports
          path: ./reports/relatorio.html

